Repository valohai/valohai-cli, pull requests merged in 2022-10, with the labels that each got.

#220 Create dependabot.yml for version bumps
  .github/dependabot.yml
Labels: type:enhancement

#226 Split requirements files and update
  .github/workflows/ci.yml
  requirements-dev.in
  requirements-dev.txt
  requirements-lint.in
  requirements-lint.txt
  requirements-test.txt
  requirements-typecheck.txt
Labels: type:enhancement, dependencies

#219 Allow selecting an owner for the new project
  valohai_cli/commands/project/create.py
  valohai_cli/commands/project/link.py
Labels: type:enhancement, customer-request

#217 Bump valohai* deps to their current freshest versions
  setup.cfg
Labels: type:enhancement, size:s, customer-request

#235 Update readme to mention pipx as preferred system-wide install
  README.md
Labels: type:enhancement

#240 add linebreak before adding valohai-utils to requirements.txt
  valohai_cli/commands/yaml/step.py
Labels: type:bug, size:s
